package main

import (
	"context"
	"fmt"
	"log"

	"pso.oneidentity.com/sped/cmd"
	"pso.oneidentity.com/sped/oneim/dbx"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	"github.com/jmoiron/sqlx"
	_ "github.com/microsoft/go-mssqldb"
)

var (
	db      *sqlx.DB
	cfgFile string
)

func main() {
	Execute()
}

var (
	rootCmd = &cobra.Command{
		Use:   "sped",
		Short: "A command line editor for Identity Manager synchronization projects.",
		Long: `sped is a command line program that reads and writes aspects of synchronization projects.
sped interacts directly with the DPR tables in an Identity Manager database.`,
		PersistentPreRun: setupDBConnection,
	}
)

// Execute executes the root command.
func Execute() error {
	return rootCmd.Execute()
}

func init() {
	cobra.OnInitialize(initConfig)

	rootCmd.PersistentFlags().StringVarP(&cfgFile, "config-file", "C", "", "optional database config file (host, port, database, user, password)")
	rootCmd.PersistentFlags().StringP("user", "u", "", "database user name")
	rootCmd.PersistentFlags().StringP("password", "p", "", "database password (consider using the SPED_PASSWORD env variable instead)")
	rootCmd.PersistentFlags().StringP("host", "H", "", "database host")
	rootCmd.PersistentFlags().IntP("port", "P", 1433, "database port")
	rootCmd.PersistentFlags().StringP("database", "d", "", "database name")

	rootCmd.AddCommand(cmd.VersionCmd)

	rootCmd.AddCommand(cmd.ShellCmd)
	cmd.ShowShellCmd.Flags().StringP("id", "i", "", "sync project identifier")
	cmd.ShellCmd.AddCommand(cmd.ShowShellCmd)
	cmd.InsertShellCmd.Flags().StringP("name", "n", "", "project name")
	cmd.InsertShellCmd.MarkFlagRequired("name")
	cmd.ShellCmd.AddCommand(cmd.InsertShellCmd)
	cmd.UpdateShellCmd.Flags().StringP("id", "i", "", "sync project identifier")
	cmd.InsertShellCmd.MarkFlagRequired("id")
	cmd.UpdateShellCmd.Flags().StringP("content", "c", "", "JSON content containing updated fields")
	cmd.UpdateShellCmd.MarkFlagRequired("content")
	cmd.ShellCmd.AddCommand(cmd.UpdateShellCmd)

	cmd.WorkflowCmd.PersistentFlags().StringP("shell", "s", "", "sync project")
	rootCmd.AddCommand(cmd.WorkflowCmd)
	cmd.WorkflowCmd.AddCommand(cmd.ShowWorkflowCmd)
	cmd.ShowWorkflowCmd.Flags().StringP("id", "i", "", "sync workflow identifier")
	cmd.WorkflowCmd.AddCommand(cmd.InsertWorkflowCmd)
	cmd.InsertWorkflowCmd.Flags().StringP("name", "n", "", "workflow name")
	cmd.InsertWorkflowCmd.MarkFlagRequired("name")
	cmd.InsertWorkflowCmd.Flags().StringP("direction", "", "", "Direction of synchronization for workflow: one of Inherite, ToTheLeft, ToTheRight")

	cmd.UpdateWorkflowCmd.Flags().StringP("id", "i", "", "workflow identifier (UID_DPRProjectionConfig)")
	cmd.UpdateWorkflowCmd.MarkFlagRequired("id")
	cmd.UpdateWorkflowCmd.Flags().StringP("content", "c", "", "JSON content containing updated fields")
	cmd.UpdateWorkflowCmd.MarkFlagRequired("content")
	cmd.WorkflowCmd.AddCommand(cmd.UpdateWorkflowCmd)
	cmd.AddConnectionToWorkflowCmd.Flags().StringP("id", "i", "", "sync project identifier")
	cmd.AddConnectionToWorkflowCmd.MarkFlagRequired("id")
	cmd.AddConnectionToWorkflowCmd.Flags().StringP("connection-id", "", "", "system connection identifier (UID_DPRSystemConnection)")
	cmd.AddConnectionToWorkflowCmd.MarkFlagRequired("connection-id")
	cmd.WorkflowCmd.AddCommand(cmd.AddConnectionToWorkflowCmd)
	cmd.AddAllConnectionsToWorkflowCmd.Flags().StringP("id", "i", "", "workflow identifier")
	cmd.AddAllConnectionsToWorkflowCmd.MarkFlagRequired("id")
	cmd.WorkflowCmd.AddCommand(cmd.AddAllConnectionsToWorkflowCmd)

	cmd.WorkflowStepCmd.PersistentFlags().StringP("workflow-id", "w", "", "workflow UID")
	rootCmd.AddCommand(cmd.WorkflowStepCmd)
	cmd.WorkflowStepCmd.AddCommand(cmd.ShowWorkflowStepCmd)
	cmd.ShowWorkflowStepCmd.Flags().StringP("id", "i", "", "workflow step identifier")
	cmd.InsertWorkflowStepCmd.Flags().StringP("name", "n", "", "workflow step name")
	cmd.InsertWorkflowStepCmd.MarkFlagRequired("name")
	cmd.InsertWorkflowStepCmd.Flags().StringP("map-id", "", "", "system map (UID_DPRSystemMap)")
	cmd.InsertWorkflowStepCmd.MarkFlagRequired("map-id")
	cmd.InsertWorkflowStepCmd.Flags().StringP("left-connection-id", "", "", "id of left connection (UID_DPRSystemConnection")
	cmd.InsertWorkflowStepCmd.Flags().StringP("right-connection-id", "", "", "id of right connection (UID_DPRSystemConnection")
	cmd.InsertWorkflowStepCmd.Flags().StringP("match-sets-id", "", "", "id of match set collection (UID_DPRSystemObjectMatchSets")
	cmd.InsertWorkflowStepCmd.Flags().BoolP("include-default-match-sets", "", true, "include default set of Match Sets")
	cmd.InsertWorkflowStepCmd.Flags().BoolP("use-default-connections", "", true, "include default connections (Identity Manager + target system)")
	cmd.WorkflowStepCmd.AddCommand(cmd.InsertWorkflowStepCmd)
	cmd.UpdateWorkflowStepCmd.Flags().StringP("id", "i", "", "workflow step identifier")
	cmd.UpdateWorkflowStepCmd.MarkFlagRequired("id")
	cmd.UpdateWorkflowStepCmd.Flags().StringP("content", "c", "", "JSON content containing updated fields")
	cmd.UpdateWorkflowStepCmd.MarkFlagRequired("content")
	cmd.WorkflowStepCmd.AddCommand(cmd.UpdateWorkflowStepCmd)
	cmd.AddSchemaMethodCmd.Flags().StringP("id", "i", "", "workflow step identifier")
	cmd.AddSchemaMethodCmd.MarkFlagRequired("id")
	cmd.AddSchemaMethodCmd.Flags().StringP("side", "s", "", "apply method to Left or Right side schema")
	cmd.AddSchemaMethodCmd.MarkFlagRequired("id")
	cmd.AddSchemaMethodCmd.Flags().StringP("method", "", "", "method name (Insert, Update, Delete, MarkAsOutstanding, UnMarkAsOutstanding)")
	cmd.AddSchemaMethodCmd.MarkFlagRequired("method")
	cmd.AddSchemaMethodCmd.Flags().StringP("match-set", "", "", "match set name (DifferenceLeftToRight, DifferenceRightToLeft, IntersectionWithDifferences, IntersectionWithoutDifferences)")
	cmd.AddSchemaMethodCmd.MarkFlagRequired("match-set")
	cmd.WorkflowStepCmd.AddCommand(cmd.AddSchemaMethodCmd)

	rootCmd.AddCommand(cmd.StepQuotaCmd)
	cmd.StepQuotaCmd.AddCommand(cmd.ShowStepQuotaCmd)
	cmd.ShowStepQuotaCmd.Flags().StringP("id", "i", "", "workflow step identifier")
	cmd.InsertStepQuotaCmd.Flags().StringP("name", "n", "", "workflow step name")
	cmd.InsertStepQuotaCmd.MarkFlagRequired("name")
	cmd.InsertStepQuotaCmd.Flags().StringP("type", "t", "", "quota type, NoQuota or DefinedThresholds")
	cmd.InsertStepQuotaCmd.MarkFlagRequired("type")
	cmd.StepQuotaCmd.AddCommand(cmd.InsertStepQuotaCmd)
	cmd.UpdateStepQuotaCmd.Flags().StringP("id", "i", "", "workflow step quota identifier (DPRProjectionStepQuota)")
	cmd.UpdateStepQuotaCmd.MarkFlagRequired("id")
	cmd.UpdateStepQuotaCmd.Flags().StringP("content", "c", "", "JSON content containing updated fields")
	cmd.UpdateStepQuotaCmd.MarkFlagRequired("content")
	cmd.StepQuotaCmd.AddCommand(cmd.UpdateStepQuotaCmd)

	cmd.ConnectionCmd.PersistentFlags().StringP("shell", "s", "", "sync project")
	rootCmd.AddCommand(cmd.ConnectionCmd)
	cmd.ConnectionCmd.AddCommand(cmd.ShowConnectionCmd)
	cmd.ShowConnectionCmd.Flags().StringP("id", "i", "", "sync Connection identifier")
	cmd.ConnectionCmd.AddCommand(cmd.InsertConnectionCmd)
	cmd.InsertConnectionCmd.Flags().StringP("name", "n", "", "Connection name")
	cmd.InsertConnectionCmd.MarkFlagRequired("name")
	cmd.InsertConnectionCmd.Flags().StringP("type", "t", "", "MainConnection or ConnectedSystemConnection")
	cmd.InsertConnectionCmd.Flags().StringP("connector-type", "", "", "connector type identifier, i.e. VI.Xxxx.Xxxx")
	cmd.InsertConnectionCmd.Flags().StringP("connection-string", "c", "", "system-dependent connection string")
	cmd.InsertConnectionCmd.Flags().StringP("schema-id", "", "", "schema associated with connection (UID_DPRSchema)")
	cmd.InsertConnectionCmd.MarkFlagRequired("schema-id")
	cmd.InsertOneIMConnectionCmd.Flags().StringP("connection-string", "c", "", "database connection string")
	cmd.ConnectionCmd.AddCommand(cmd.InsertOneIMConnectionCmd)
	cmd.InsertTargetSystemConnectionCmd.Flags().StringP("connector-type", "c", "VI.Projector.Powershell.PoshConnectorDescriptor", "connector type identifier, i.e. VI.Xxxx.Xxxx")
	cmd.InsertTargetSystemConnectionCmd.Flags().StringP("connection-string", "", "", "system-dependent connection string")
	cmd.InsertTargetSystemConnectionCmd.Flags().StringP("connection-string-type", "", "", "connector string type identifier, i.e. VI.Xxxx.Xxxx")
	cmd.ConnectionCmd.AddCommand(cmd.InsertTargetSystemConnectionCmd)
	cmd.UpdateConnectionCmd.Flags().StringP("id", "i", "", "sync Connection identifier")
	cmd.UpdateConnectionCmd.MarkFlagRequired("id")
	cmd.UpdateConnectionCmd.Flags().StringP("content", "c", "", "JSON content containing updated fields")
	cmd.UpdateConnectionCmd.MarkFlagRequired("content")
	cmd.ConnectionCmd.AddCommand(cmd.UpdateConnectionCmd)

	cmd.VariableSetCmd.PersistentFlags().StringP("shell", "s", "", "sync project")
	rootCmd.AddCommand(cmd.VariableSetCmd)
	cmd.VariableSetCmd.AddCommand(cmd.ShowVariableSetCmd)
	cmd.ShowVariableSetCmd.Flags().StringP("id", "i", "", "sync VariableSet identifier")
	cmd.VariableSetCmd.AddCommand(cmd.InsertVariableSetCmd)
	cmd.InsertVariableSetCmd.Flags().StringP("name", "n", "", "VariableSet name")
	cmd.InsertVariableSetCmd.Flags().StringP("parent-id", "", "", "parent VariableSet name")
	cmd.UpdateVariableSetCmd.Flags().StringP("id", "i", "", "sync VariableSet identifier")
	cmd.UpdateVariableSetCmd.MarkFlagRequired("id")
	cmd.UpdateVariableSetCmd.Flags().StringP("content", "c", "", "JSON content containing updated fields")
	cmd.UpdateVariableSetCmd.MarkFlagRequired("content")
	cmd.VariableSetCmd.AddCommand(cmd.UpdateVariableSetCmd)

	cmd.VariableCmd.PersistentFlags().StringP("variable-set-id", "", "", "parent variable set (UID_DPRVariableSet)")
	rootCmd.AddCommand(cmd.VariableCmd)
	cmd.VariableCmd.AddCommand(cmd.ShowVariableCmd)
	cmd.ShowVariableCmd.Flags().StringP("id", "i", "", "sync Variable identifier")
	cmd.VariableCmd.AddCommand(cmd.InsertVariableCmd)
	cmd.InsertVariableCmd.Flags().StringP("name", "n", "", "Variable name")
	cmd.InsertVariableCmd.MarkFlagRequired("name")
	cmd.InsertVariableCmd.Flags().StringP("value", "v", "", "Variable value")
	cmd.InsertVariableCmd.Flags().BoolP("secret", "", false, "Variable value is sensitive")
	cmd.UpdateVariableCmd.Flags().StringP("id", "i", "", "sync Variable identifier")
	cmd.UpdateVariableCmd.MarkFlagRequired("id")
	cmd.UpdateVariableCmd.Flags().StringP("content", "c", "", "JSON content containing updated fields")
	cmd.UpdateVariableCmd.MarkFlagRequired("content")
	cmd.VariableCmd.AddCommand(cmd.UpdateVariableCmd)

	cmd.SchemaCmd.PersistentFlags().StringP("shell", "s", "", "sync project")
	rootCmd.AddCommand(cmd.SchemaCmd)
	cmd.SchemaCmd.AddCommand(cmd.ShowSchemaCmd)
	cmd.ShowSchemaCmd.Flags().StringP("id", "i", "", "sync Schema identifier")
	cmd.SchemaCmd.AddCommand(cmd.InsertSchemaCmd)
	cmd.InsertSchemaCmd.Flags().StringP("name", "n", "", "Schema name")
	cmd.InsertSchemaCmd.MarkFlagRequired("name")
	cmd.InsertSchemaCmd.Flags().StringP("system-id", "", "", "unique identifier of system (UID_DialogDatabase for OneIM connection)")
	cmd.InsertSchemaCmd.MarkFlagRequired("system-id")
	cmd.InsertSchemaCmd.Flags().StringP("clr-name", "", "", "full name of target system type (UID_QBMClrType)")
	cmd.InsertSchemaCmd.MarkFlagRequired("clr-name")
	cmd.InsertOneIMSchemaCmd.Flags().StringP("name", "n", "", "Schema name")
	cmd.InsertOneIMSchemaCmd.MarkFlagRequired("name")
	cmd.SchemaCmd.AddCommand(cmd.InsertOneIMSchemaCmd)
	cmd.UpdateSchemaCmd.Flags().StringP("id", "i", "", "sync Schema identifier")
	cmd.InsertCustomSchemaCmd.Flags().StringP("name", "n", "", "Schema name")
	cmd.InsertCustomSchemaCmd.MarkFlagRequired("name")
	cmd.InsertCustomSchemaCmd.Flags().StringP("system-id", "", "", "short name to uniquely identity instance of target system (e.g. FQDN)")
	cmd.InsertCustomSchemaCmd.MarkFlagRequired("system-id")
	cmd.SchemaCmd.AddCommand(cmd.InsertCustomSchemaCmd)
	cmd.UpdateSchemaCmd.MarkFlagRequired("id")
	cmd.UpdateSchemaCmd.Flags().StringP("content", "c", "", "JSON content containing updated fields")
	cmd.UpdateSchemaCmd.MarkFlagRequired("content")
	cmd.SchemaCmd.AddCommand(cmd.UpdateSchemaCmd)

	cmd.SchemaTypeCmd.PersistentFlags().StringP("schema-id", "", "", "schema identifier")
	rootCmd.AddCommand(cmd.SchemaTypeCmd)
	cmd.ShowSchemaTypeCmd.Flags().StringP("id", "i", "", "sync schema type identifier")
	cmd.SchemaTypeCmd.AddCommand(cmd.ShowSchemaTypeCmd)
	cmd.InsertSchemaTypeCmd.Flags().StringP("name", "n", "", "schema type name")
	cmd.InsertSchemaTypeCmd.Flags().StringP("clr-name", "", "", "full name of target system object type")
	cmd.SchemaTypeCmd.AddCommand(cmd.InsertSchemaTypeCmd)
	cmd.UpdateSchemaTypeCmd.Flags().StringP("id", "i", "", "schema type identifier")
	cmd.UpdateSchemaTypeCmd.MarkFlagRequired("id")
	cmd.UpdateSchemaTypeCmd.Flags().StringP("content", "c", "", "JSON content containing updated fields")
	cmd.UpdateSchemaTypeCmd.MarkFlagRequired("content")
	cmd.SchemaTypeCmd.AddCommand(cmd.UpdateSchemaTypeCmd)
	cmd.AddSchemaMethodsCmd.Flags().StringP("id", "i", "", "schema type identifier")
	cmd.AddSchemaMethodsCmd.MarkFlagRequired("id")
	cmd.AddSchemaMethodsCmd.Flags().StringP("methods", "m", "", "space separated list of method names")
	cmd.AddSchemaMethodsCmd.Flags().BoolP("all", "a", false, "add all valid methods, for Identity Manager schemas")
	cmd.AddSchemaMethodsCmd.Flags().StringP("clr-name", "", "", "full name of method object type")
	cmd.SchemaTypeCmd.AddCommand(cmd.AddSchemaMethodsCmd)
	cmd.AddOneIMSchemaPropertiesCmd.Flags().StringP("id", "i", "", "schema type identifier")
	cmd.AddOneIMSchemaPropertiesCmd.MarkFlagRequired("id")
	cmd.SchemaTypeCmd.AddCommand(cmd.AddOneIMSchemaPropertiesCmd)
	cmd.AddDefaultSchemaClassCmd.Flags().StringP("id", "i", "", "schema type identifier")
	cmd.AddDefaultSchemaClassCmd.MarkFlagRequired("id")
	cmd.SchemaTypeCmd.AddCommand(cmd.AddDefaultSchemaClassCmd)

	cmd.SchemaClassCmd.PersistentFlags().StringP("schema-type-id", "", "", "schema type identifier (UID_DPRSchemaType)")
	rootCmd.AddCommand(cmd.SchemaClassCmd)
	cmd.SchemaClassCmd.AddCommand(cmd.ShowSchemaClassCmd)
	cmd.ShowSchemaClassCmd.Flags().StringP("id", "i", "", "sync schema class identifier")
	cmd.SchemaClassCmd.AddCommand(cmd.InsertSchemaClassCmd)
	cmd.InsertSchemaClassCmd.Flags().StringP("name", "n", "", "schema class name")
	cmd.InsertSchemaClassCmd.Flags().StringP("clr-name", "", "", "full name of target system object type)")
	cmd.UpdateSchemaClassCmd.Flags().StringP("id", "i", "", "schema class identifier")
	cmd.UpdateSchemaClassCmd.MarkFlagRequired("id")
	cmd.UpdateSchemaClassCmd.Flags().StringP("content", "c", "", "JSON content containing updated fields")
	cmd.UpdateSchemaClassCmd.MarkFlagRequired("content")
	cmd.SchemaClassCmd.AddCommand(cmd.UpdateSchemaClassCmd)

	cmd.SchemaMethodCmd.PersistentFlags().StringP("schema-type-id", "", "", "schema type identifier (UID_DPRSchemaType)")
	rootCmd.AddCommand(cmd.SchemaMethodCmd)
	cmd.SchemaMethodCmd.AddCommand(cmd.ShowSchemaMethodCmd)
	cmd.ShowSchemaMethodCmd.Flags().StringP("id", "i", "", "sync schema class identifier")
	cmd.SchemaMethodCmd.AddCommand(cmd.InsertSchemaMethodCmd)
	cmd.InsertSchemaMethodCmd.Flags().StringP("name", "n", "", "schema method name (Insert, Update, Delete, MarkAsOutstanding, UnmarkAsOutstanding)")
	cmd.InsertSchemaMethodCmd.MarkFlagRequired("name")
	cmd.InsertSchemaMethodCmd.Flags().StringP("clr-name", "", "", "full name of method object type")
	cmd.UpdateSchemaMethodCmd.Flags().StringP("id", "i", "", "schema method identifier")
	cmd.UpdateSchemaMethodCmd.MarkFlagRequired("id")
	cmd.UpdateSchemaMethodCmd.Flags().StringP("content", "c", "", "JSON content containing updated fields")
	cmd.UpdateSchemaMethodCmd.MarkFlagRequired("content")
	cmd.SchemaMethodCmd.AddCommand(cmd.UpdateSchemaMethodCmd)

	cmd.SchemaPropertyCmd.PersistentFlags().StringP("schema-type-id", "", "", "schema type identifier (UID_DPRSchemaType)")
	rootCmd.AddCommand(cmd.SchemaPropertyCmd)
	cmd.SchemaPropertyCmd.AddCommand(cmd.ShowSchemaPropertyCmd)
	cmd.ShowSchemaPropertyCmd.Flags().StringP("id", "i", "", "sync schema class identifier")
	cmd.SchemaPropertyCmd.AddCommand(cmd.InsertSchemaPropertyCmd)
	cmd.InsertSchemaPropertyCmd.Flags().StringP("name", "n", "", "schema property name")
	cmd.InsertSchemaPropertyCmd.MarkFlagRequired("name")
	cmd.InsertSchemaPropertyCmd.Flags().StringP("clr-name", "", "", "full name of property object type")
	cmd.InsertSchemaPropertyCmd.Flags().StringP("data-type", "", "", "property type (string, int, etc.)")
	cmd.InsertSchemaPropertyCmd.MarkFlagRequired("data-type")
	cmd.UpdateSchemaPropertyCmd.Flags().StringP("id", "i", "", "schema property identifier")
	cmd.UpdateSchemaPropertyCmd.MarkFlagRequired("id")
	cmd.UpdateSchemaPropertyCmd.Flags().StringP("content", "c", "", "JSON content containing updated fields")
	cmd.UpdateSchemaPropertyCmd.MarkFlagRequired("content")
	cmd.SchemaPropertyCmd.AddCommand(cmd.UpdateSchemaPropertyCmd)

	cmd.SystemMapCmd.PersistentFlags().StringP("shell", "s", "", "project identifier (UID_DPRShell)")
	rootCmd.AddCommand(cmd.SystemMapCmd)
	cmd.SystemMapCmd.AddCommand(cmd.ShowSystemMapCmd)
	cmd.ShowSystemMapCmd.Flags().StringP("id", "i", "", "sync map identifier")
	cmd.InsertSystemMapCmd.Flags().StringP("name", "n", "", "map name")
	cmd.InsertSystemMapCmd.MarkFlagRequired("name")
	cmd.InsertSystemMapCmd.Flags().StringP("left-schema-class-id", "", "", "UID_DPRSchemaClass on left side of map")
	cmd.InsertSystemMapCmd.MarkFlagRequired("left-schema-class-id")
	cmd.InsertSystemMapCmd.Flags().StringP("right-schema-class-id", "", "", "UID_DPRSchemaClass on right side of map")
	cmd.InsertSystemMapCmd.MarkFlagRequired("right-schema-class-id")
	cmd.InsertSystemMapCmd.Flags().StringP("direction", "", "BothDirections", "One of ToTheLeft, ToTheRight, or BothDirections")
	cmd.SystemMapCmd.AddCommand(cmd.InsertSystemMapCmd)
	cmd.InsertSystemMapByNameCmd.Flags().StringP("name", "n", "", "map name")
	cmd.InsertSystemMapByNameCmd.MarkFlagRequired("name")
	cmd.InsertSystemMapByNameCmd.Flags().StringP("left", "l", "", "name of schema class on left side of map")
	cmd.InsertSystemMapByNameCmd.MarkFlagRequired("left")
	cmd.InsertSystemMapByNameCmd.Flags().StringP("right", "r", "", "name of schema class on right side of map")
	cmd.InsertSystemMapByNameCmd.MarkFlagRequired("right")
	cmd.InsertSystemMapByNameCmd.Flags().StringP("direction", "", "BothDirections", "One of ToTheLeft, ToTheRight, or BothDirections")
	cmd.SystemMapCmd.AddCommand(cmd.InsertSystemMapByNameCmd)
	cmd.UpdateSystemMapCmd.Flags().StringP("id", "i", "", "map identifier")
	cmd.UpdateSystemMapCmd.MarkFlagRequired("id")
	cmd.UpdateSystemMapCmd.Flags().StringP("content", "c", "", "JSON content containing updated fields")
	cmd.UpdateSystemMapCmd.MarkFlagRequired("content")
	cmd.SystemMapCmd.AddCommand(cmd.UpdateSystemMapCmd)

	cmd.MappingRuleCmd.PersistentFlags().StringP("map-id", "m", "", "UID_DPRSystemMap")
	rootCmd.AddCommand(cmd.MappingRuleCmd)
	cmd.MappingRuleCmd.AddCommand(cmd.ShowMappingRuleCmd)
	cmd.ShowMappingRuleCmd.Flags().StringP("id", "i", "", "mapping rule identifier")
	cmd.InsertMappingRuleCmd.Flags().StringP("clr-name", "", "VI.Projector.Mapping.Rules.SinglePropertyComparisonRule", "full name of mapping rule CLR type")
	cmd.InsertMappingRuleCmd.Flags().StringP("name", "n", "", "mapping rule name")
	cmd.InsertMappingRuleCmd.MarkFlagRequired("name")
	cmd.InsertMappingRuleCmd.Flags().StringP("left-property", "l", "", "name of property on left side")
	cmd.InsertMappingRuleCmd.MarkFlagRequired("left-property")
	cmd.InsertMappingRuleCmd.Flags().StringP("right-property", "r", "", "name of property on right side")
	cmd.InsertMappingRuleCmd.MarkFlagRequired("right-property")
	cmd.InsertMappingRuleCmd.Flags().StringP("direction", "", "Inherite", "one of Inherite, ToTheLeft, ToTheRight, DoNotMap")
	cmd.MappingRuleCmd.AddCommand(cmd.InsertMappingRuleCmd)

	cmd.AddKeyBasedRuleCmd.Flags().StringP("name", "n", "", "mapping rule name")
	cmd.AddKeyBasedRuleCmd.MarkFlagRequired("name")
	cmd.AddKeyBasedRuleCmd.Flags().StringP("left-property", "l", "", "name of property on left side")
	cmd.AddKeyBasedRuleCmd.MarkFlagRequired("left-property")
	cmd.AddKeyBasedRuleCmd.Flags().StringP("right-property", "r", "", "name of property on right side")
	cmd.AddKeyBasedRuleCmd.MarkFlagRequired("right-property")
	cmd.AddKeyBasedRuleCmd.Flags().StringP("lookup-table", "", "", "Identity Manager table containing the value used in the map")
	cmd.AddKeyBasedRuleCmd.MarkFlagRequired("lookup-table")
	cmd.AddKeyBasedRuleCmd.Flags().StringP("right-key-attribute", "", "", "name of attribute in lookup table that contains the value in right side of the mapping")
	cmd.AddKeyBasedRuleCmd.MarkFlagRequired("right-key-attribute")
	cmd.AddKeyBasedRuleCmd.Flags().StringP("left-key-attribute", "", "", "name of attribute in lookup table that will be used in the left side of the mapping")
	cmd.AddKeyBasedRuleCmd.MarkFlagRequired("left-key-attribute")
	cmd.MappingRuleCmd.AddCommand(cmd.AddKeyBasedRuleCmd)

	cmd.InsertMatchingRuleCmd.Flags().StringP("clr-name", "", "VI.Projector.Mapping.Rules.SinglePropertyComparisonRule", "full name of mapping rule CLR type")
	cmd.InsertMatchingRuleCmd.Flags().StringP("name", "n", "", "mapping rule name")
	cmd.InsertMatchingRuleCmd.MarkFlagRequired("name")
	cmd.InsertMatchingRuleCmd.Flags().StringP("left-property", "l", "", "name of property on left side")
	cmd.InsertMatchingRuleCmd.MarkFlagRequired("left-property")
	cmd.InsertMatchingRuleCmd.Flags().StringP("right-property", "r", "", "name of property on right side")
	cmd.InsertMatchingRuleCmd.MarkFlagRequired("right-property")
	cmd.MappingRuleCmd.AddCommand(cmd.InsertMatchingRuleCmd)
	cmd.UpdateMappingRuleCmd.Flags().StringP("id", "i", "", "mapping rule identifier")
	cmd.UpdateMappingRuleCmd.MarkFlagRequired("id")
	cmd.UpdateMappingRuleCmd.Flags().StringP("content", "c", "", "JSON content containing updated fields")
	cmd.UpdateMappingRuleCmd.MarkFlagRequired("content")
	cmd.MappingRuleCmd.AddCommand(cmd.UpdateMappingRuleCmd)

	rootCmd.AddCommand(cmd.MatchSetsCmd)
	cmd.MatchSetsCmd.AddCommand(cmd.ShowMatchSetsCmd)
	cmd.ShowMatchSetsCmd.Flags().StringP("id", "i", "", "object match sets identifier")
	cmd.InsertMatchSetsCmd.Flags().StringP("name", "n", "", "object match sets name")
	cmd.InsertMatchSetsCmd.MarkFlagRequired("name")
	cmd.MatchSetsCmd.AddCommand(cmd.InsertMatchSetsCmd)
	cmd.UpdateMatchSetsCmd.Flags().StringP("id", "i", "", "object match sets identifier")
	cmd.UpdateMatchSetsCmd.MarkFlagRequired("id")
	cmd.UpdateMatchSetsCmd.Flags().StringP("content", "c", "", "JSON content containing updated fields")
	cmd.UpdateMatchSetsCmd.MarkFlagRequired("content")
	cmd.MatchSetsCmd.AddCommand(cmd.UpdateMatchSetsCmd)
	cmd.MatchSetsCmd.AddCommand(cmd.AddDefaultMatchSetsCmd)
	cmd.AddDefaultMatchSetsCmd.Flags().StringP("id", "i", "", "object match sets identifier")
	cmd.AddDefaultMatchSetsCmd.MarkFlagRequired("id")

	rootCmd.AddCommand(cmd.SingleMatchSetCmd)
	cmd.ShowSingleMatchSetCmd.Flags().StringP("id", "i", "", "object match set identifier")
	cmd.SingleMatchSetCmd.AddCommand(cmd.ShowSingleMatchSetCmd)
	cmd.InsertSingleMatchSetCmd.Flags().StringP("name", "n", "", "object match set name")
	cmd.InsertSingleMatchSetCmd.MarkFlagRequired("name")
	cmd.SingleMatchSetCmd.AddCommand(cmd.InsertSingleMatchSetCmd)

	cmd.StartInfoCmd.PersistentFlags().StringP("shell", "s", "", "sync project")
	rootCmd.AddCommand(cmd.StartInfoCmd)
	cmd.StartInfoCmd.AddCommand(cmd.ShowStartInfoCmd)
	cmd.ShowStartInfoCmd.Flags().StringP("id", "i", "", "sync StartInfo identifier")
	cmd.StartInfoCmd.AddCommand(cmd.InsertStartInfoCmd)
	cmd.InsertStartInfoCmd.Flags().StringP("name", "n", "", "StartInfo name")
	cmd.InsertStartInfoCmd.MarkFlagRequired("name")
	cmd.InsertStartInfoCmd.Flags().StringP("variable-set-id", "", "", "variable set identifier")
	cmd.InsertStartInfoCmd.Flags().BoolP("use-default-variables", "", true, "use the default variable set of shell")
	cmd.InsertStartInfoCmd.Flags().StringP("workflow-id", "", "", "workflow identifier")
	cmd.InsertStartInfoCmd.Flags().StringP("workflow-name", "", "", "workflow name (workflow id has precedence)")
	cmd.InsertStartInfoCmd.Flags().StringP("direction", "", "", "Direction of synchronization: one of Inherite, ToTheLeft, ToTheRight")
	cmd.InsertStartInfoCmd.MarkFlagRequired("direction")
	cmd.UpdateStartInfoCmd.Flags().StringP("id", "i", "", "sync StartInfo identifier")
	cmd.UpdateStartInfoCmd.MarkFlagRequired("id")
	cmd.UpdateStartInfoCmd.Flags().StringP("content", "c", "", "JSON content containing updated fields")
	cmd.UpdateStartInfoCmd.MarkFlagRequired("content")
	cmd.StartInfoCmd.AddCommand(cmd.UpdateStartInfoCmd)
	cmd.AddScheduleToStartInfoCmd.Flags().StringP("id", "i", "", "StartInfo identifier")
	cmd.AddScheduleToStartInfoCmd.MarkFlagRequired("id")
	cmd.AddScheduleToStartInfoCmd.Flags().StringP("time-zone", "", "UTC", "short name of schedule time zone")
	cmd.AddScheduleToStartInfoCmd.Flags().StringP("type", "", "Day", "type of schedule (Hour, Day, Week, etc.)")
	cmd.AddScheduleToStartInfoCmd.Flags().IntP("frequency", "", 1, "how often to run schedule - n per hour/day/week etc.")
	cmd.AddScheduleToStartInfoCmd.Flags().StringP("start-time", "", "00:00", "time of day to run sync, in hh:mm 24hr format")
	cmd.StartInfoCmd.AddCommand(cmd.AddScheduleToStartInfoCmd)
	cmd.AddRootObjectToStartInfoCmd.Flags().StringP("id", "i", "", "StartInfo identifier")
	cmd.AddRootObjectToStartInfoCmd.MarkFlagRequired("id")
	cmd.AddRootObjectToStartInfoCmd.Flags().StringP("root-object-key", "", "", "object key of root object")
	cmd.AddRootObjectToStartInfoCmd.Flags().StringP("table-name", "", "", "name of target table (root-object-key takes precedence)")
	cmd.AddRootObjectToStartInfoCmd.Flags().StringP("connection-id", "", "", "connection identifier of target system")
	cmd.AddRootObjectToStartInfoCmd.Flags().BoolP("use-default-connection", "", true, "use default target system connection")
	cmd.AddRootObjectToStartInfoCmd.Flags().StringP("variable-set-id", "", "", "variable set identifier")
	cmd.AddRootObjectToStartInfoCmd.Flags().BoolP("use-default-variables", "", true, "use default variable set")
	cmd.AddRootObjectToStartInfoCmd.Flags().StringP("server-id", "", "", "server identifier")
	cmd.AddRootObjectToStartInfoCmd.Flags().StringP("server-name", "", "", "server name (server-id takes precedence)")
	cmd.StartInfoCmd.AddCommand(cmd.AddRootObjectToStartInfoCmd)
	cmd.RunStartInfoCmd.Flags().StringP("id", "i", "", "StartInfo identifier")
	cmd.RunStartInfoCmd.MarkFlagRequired("id")
	cmd.StartInfoCmd.AddCommand(cmd.RunStartInfoCmd)
	cmd.GetRunStatusCmd.Flags().StringP("id", "i", "", "StartInfo identifier")
	cmd.GetRunStatusCmd.MarkFlagRequired("id")
	cmd.GetRunStatusCmd.Flags().StringP("job-id", "j", "", "synchronization job identifier (UID_Job)")
	cmd.GetRunStatusCmd.MarkFlagRequired("job-id")
	cmd.StartInfoCmd.AddCommand(cmd.GetRunStatusCmd)

	rootCmd.AddCommand(cmd.ScheduleCmd)
	cmd.ScheduleCmd.AddCommand(cmd.ShowScheduleCmd)
	cmd.ShowScheduleCmd.Flags().StringP("id", "i", "", "sync Schedule identifier")
	cmd.ScheduleCmd.AddCommand(cmd.InsertScheduleCmd)
	cmd.InsertScheduleCmd.Flags().StringP("name", "n", "", "Schedule name")
	cmd.InsertScheduleCmd.MarkFlagRequired("name")
	cmd.UpdateScheduleCmd.Flags().StringP("id", "i", "", "sync Schedule identifier")
	cmd.UpdateScheduleCmd.MarkFlagRequired("id")
	cmd.UpdateScheduleCmd.Flags().StringP("content", "c", "", "JSON content containing updated fields")
	cmd.UpdateScheduleCmd.MarkFlagRequired("content")
	cmd.ScheduleCmd.AddCommand(cmd.UpdateScheduleCmd)

	rootCmd.AddCommand(cmd.DialogDatabaseCmd)
	cmd.DialogDatabaseCmd.AddCommand(cmd.ShowDialogDatabaseCmd)
	cmd.ShowDialogDatabaseCmd.Flags().StringP("id", "i", "", "database identifier")

	rootCmd.AddCommand(cmd.ClrTypeCmd)
	cmd.ClrTypeCmd.AddCommand(cmd.ShowClrTypeCmd)
	cmd.ShowClrTypeCmd.Flags().StringP("id", "i", "", "type identifier (UID_QBMClrType)")
	cmd.ShowClrTypeCmd.Flags().StringP("name", "n", "", "fully qualified name of CLR type")

	rootCmd.AddCommand(cmd.FileCmd)
	cmd.ShowFilesCmd.Flags().StringP("id", "i", "", "file identifier (UID_QBMFileRevision)")
	cmd.FileCmd.AddCommand(cmd.ShowFilesCmd)
	cmd.InsertFileCmd.Flags().StringP("file", "f", "", "file path")
	cmd.InsertFileCmd.Flags().StringP("file-version", "", "", "version string associated with file")
	cmd.InsertFileCmd.MarkFlagRequired("file")
	cmd.InsertFileCmd.MarkFlagRequired("file-version")
	cmd.FileCmd.AddCommand(cmd.InsertFileCmd)
	cmd.AssignDeployTargetCmd.Flags().StringP("id", "i", "", "file identifier (UID_QBMFileRevision)")
	cmd.AssignDeployTargetCmd.MarkFlagRequired("id")
	cmd.AssignDeployTargetCmd.Flags().StringP("deploy-target", "", "Server", "Name of deploy target")
	cmd.FileCmd.AddCommand(cmd.AssignDeployTargetCmd)
	cmd.SyncFilesCmd.Flags().StringP("server-name", "", "", "Name of job server (QBMServer.Ident_Server)")
	cmd.FileCmd.AddCommand(cmd.SyncFilesCmd)
	cmd.FileCmd.AddCommand(cmd.UpdateModuleInfoCmd)

	viper.BindPFlag("config-file", rootCmd.PersistentFlags().Lookup("config-file"))
	viper.BindPFlag("host", rootCmd.PersistentFlags().Lookup("host"))
	viper.BindPFlag("port", rootCmd.PersistentFlags().Lookup("port"))
	viper.BindPFlag("database", rootCmd.PersistentFlags().Lookup("database"))
	viper.BindPFlag("user", rootCmd.PersistentFlags().Lookup("user"))
	viper.BindPFlag("password", rootCmd.PersistentFlags().Lookup("password"))
}

func initConfig() {

	if cfgFile != "" {
		viper.SetConfigFile(cfgFile)
		if err := viper.ReadInConfig(); err != nil {
			fmt.Println("failed to read config file " + cfgFile)
		}
	}

	viper.SetEnvPrefix("SPED")
	viper.AutomaticEnv()

}

func setupDBConnection(c *cobra.Command, args []string) {
	//host, _ := c.Flags().GetString("host")
	host := viper.GetString("host")
	port := viper.GetInt("port")
	database := viper.GetString("database")
	username := viper.GetString("user")
	password := viper.GetString("password")

	db, err := dbx.CreateCtx(username, password, host, port, database, 5)
	if err != nil {
		log.Println(err)
		return
	}

	// no need for name mangling
	db.MapperFunc(nil)

	ctx := context.WithValue(c.Context(), "db_connection", db)
	c.SetContext(ctx)
}
